#!/usr/bin/env php
<?php

$birthDate = "1988-08-18";
$todayDate = date("Y-m-d");
$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime - $birthTime;
$totalDays = floor($totalSecs /3600 /24);
echo "$totalDays \n ";

?>
